# Clustering Lab

 
Based of the amazing work you did in the Movie Industry you've been recruited to the NBA! You are working as the VP of Analytics that helps support a head scout, Mr. Rooney, for the worst team in the NBA probably the Wizards. Mr. Rooney just heard about Data Science and thinks it can solve all the team's problems!!! He wants you to figure out a way to find players that are high performing but maybe not highly paid that you can steal to get the team to the playoffs! 

In this document you will work through a similar process that we did in class with the NBA data (NBA_Perf_22 and nba_salaries_22), merging them together. This is from 22-23 season, feel free to update to 2023-24 season if you want.
# Data Sources:

https://www.basketball-reference.com/leagues/NBA_2024_totals.html # reference for performance data
https://www.basketball-reference.com/contracts/players.html # reference for salary data


Details: 

- Determine a way to use clustering to estimate based on performance if 
players are under or over paid, generally. 

- Then select players you believe would be best for your team and explain why. Do so in three categories: 
    * Examples that are not good choices (3 or 4) 
    * Several options that are good choices (3 or 4)
    * Several options that could work, assuming you can't get the players in the good category (3 or 4)

- You will decide the cutoffs for each category, so you should be able to explain why you chose them.

- Provide a well commented and clean report of your findings in a separate notebook that can be presented to Mr. Rooney, keeping in mind he doesn't understand...anything. Include a rationale for variables you included in the model, details on your approach and a overview of the results with supporting visualizations. 


Hints:

- Salary is the variable you are trying to understand 
- When interpreting you might want to use graphs that include variables that are the most correlated with Salary
- You'll need to scale the variables before performing the clustering
- Be specific about why you selected the players that you did, more detail is better
- Use good coding practices, comment heavily, indent, don't use for loops unless totally necessary and create modular sections that align with some outcome. If necessary create more than one script,list/load libraries at the top and don't include libraries that aren't used. 
- Be careful for non-traditional characters in the players names, certain graphs won't work when these characters are included.

In [1]:
# Importing libraries

import os
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score


# Reading the CSV files (used copilot to help handle special characters that pandas could not read)
nba_performance_22 = pd.read_csv("/workspaces/DS-3021/data/NBA_Perf_22.csv", encoding="ISO-8859-1")
nba_salaries_22 = pd.read_csv("/workspaces/DS-3021/data/nba_salaries_22.csv")

#Drop variables that will not be needed or are duplicates

print(nba_performance_22.info()) # Printing the variables from the dataset

# Dropping unnecessary columns

nba_performance = nba_performance_22.drop(columns = ['Player', 'Tm', 'Pos', 'FGA', 'FG', '3P', '3PA', '2P', '2PA', 'FT', 'FTA'])

# Dropping duplicate variables 

nba_performance = nba_performance.drop_duplicates()

nba_salaries = nba_salaries_22.drop_duplicates()

# Merging the datasets

nba_data = pd.merge(nba_performance_22[['Player']].join(nba_performance), nba_salaries_22, on = 'Player', how =  'inner')

nba_data = nba_data.dropna() # Dropping NA values

# Removing $ from the Salary column

nba_data['Salary'] = nba_data['Salary'].replace(r'[\$,]', '', regex=True)

nba_data.head() # Printing the first five rows of the merged dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 812 entries, 0 to 811
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  812 non-null    object
 1   Pos     812 non-null    object
 2   Age     812 non-null    int64
 3   Tm      812 non-null    object
 4   G       812 non-null    int64
 5   GS      812 non-null    int64
 6   MP      812 non-null    float64
 7   FG      812 non-null    float64
 8   FGA     812 non-null    float64
 9   FG%     797 non-null    float64
 10  3P      812 non-null    float64
 11  3PA     812 non-null    float64
 12  3P%     740 non-null    float64
 13  2P      812 non-null    float64
 14  2PA     812 non-null    float64
 15  2P%     784 non-null    float64
 16  eFG%    797 non-null    float64
 17  FT      812 non-null    float64
 18  FTA     812 non-null    float64
 19  FT%     715 non-null    float64
 20  ORB     812 non-null    float64
 21  DRB     812 non-null    float64
 22  TRB     812 non-null    float64
 23  AST     812 non-null    float64
 24  STL     812 non-null    float64
 25  BLK     812 non-null    float64
 26  TOV     812 non-null    float64
 27  PF      812 non-null    float64
 28  PTS     812 non-null    float64
dtypes: float64(23), int64(3), object(3)
memory usage: 184.1+ KB
None

,Player,Age,G,GS,MP,FG%,3P%,2P%,eFG%,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Salary
0,Precious Achiuwa,22.0,73.0,28.0,23.6,0.439,0.359,0.468,0.486,0.595,2.0,4.5,6.5,1.1,0.5,0.6,1.2,2.1,9.1,2840160
1,Steven Adams,28.0,76.0,75.0,26.3,0.547,0.000,0.548,0.547,0.543,4.6,5.4,10.0,3.4,0.9,0.8,1.5,2.0,6.9,17926829
2,Bam Adebayo,24.0,56.0,56.0,32.6,0.557,0.000,0.562,0.557,0.753,2.4,7.6,10.1,3.4,1.4,0.8,2.6,3.1,19.1,30351780
3,Santi Aldama,21.0,32.0,0.0,11.3,0.402,0.125,0.560,0.424,0.625,1.0,1.7,2.7,0.7,0.2,0.3,0.5,1.1,4.1,2094120
4,Nickeil Alexander-Walker,23.0,65.0,21.0,22.6,0.372,0.311,0.433,0.449,0.743,0.6,2.3,2.9,2.4,0.7,0.4,1.4,1.6,10.6,5009633

In [2]:
nba_data = nba_data.drop(columns=['Player', 'Salary']) # Dropping dependent variables

# Scaling the numeric values in the dataset

scaler = StandardScaler()

nba_scaled = scaler.fit_transform(nba_data) 

# Run the clustering algo with your best guess for K

kmeans_nba = KMeans(n_clusters = 5, random_state = 42).fit(nba_scaled)

In [3]:
#View the results

print("Centers:", kmeans_nba.cluster_centers_) 
print("Labels:", kmeans_nba.labels_)
print("Inertia:", kmeans_nba.inertia_)

Centers: [[ 0.1423482   0.15032163 -0.25558382  0.08599046 -0.39288676  0.28455326
  -0.30457223 -0.13417618  0.33805512 -0.46823813 -0.30095708 -0.37917139
  -0.05826923  0.04353688 -0.35801745 -0.19967672 -0.16265775 -0.12328638]
 [ 0.19580266  0.45193191  1.19711691  1.22809322 -0.17306458  0.26487233
  -0.22063513 -0.13596939  0.40013225 -0.16437607  0.61043789  0.41234586
   1.26913639  1.00517993  0.02067324  1.2392943   0.63713781  1.2511933 ]
 [-0.15378689  0.48002389  1.19596143  0.7329812   1.42672588 -0.90281765
   0.86751148  0.96056447 -0.69869613  2.41897504  2.07887218  2.36628016
   0.05908143  0.27839748  2.00165349  0.6181612   1.2553518   0.67104714]
 [ 0.07575663 -0.23282663 -0.54819045 -0.58831354  0.91268302 -0.25226688
   0.90153597  0.72433369 -0.55508     0.49236979 -0.11203082  0.07264426
  -0.66720705 -0.4690548   0.32470152 -0.54065627  0.08440617 -0.52275048]
 [-0.55769376 -0.78697977 -0.92676088 -1.34179545 -0.89598904 -0.140674
  -0.7309438  -0.96607817 -0.1083213  -0.65231979 -1.03789852 -1.00357598
  -0.72076235 -0.92068939 -0.69313227 -0.8377035  -1.22298095 -1.04318177]]
Labels: [3 2 2 4 0 0 4 0 2 0 0 2 3 1 1 0 4 0 0 2 3 3 3 1 1 2 1 4 1 2 1 1 3 3 3 3 0
 1 0 1 1 3 3 0 4 4 1 4 3 4 1 0 1 1 0 4 1 4 4 1 3 0 1 4 1 1 0 2 4 4 4 4 0 0
 2 0 4 4 0 3 0 0 2 3 1 0 1 1 3 3 3 3 1 1 1 1 0 1 2 0 3 3 1 3 3 1 1 0 0 4 0
 1 0 2 2 2 0 1 1 0 2 3 3 2 3 3 4 3 1 4 0 4 4 1 1 0 3 4 3 2 0 0 1 4 0 1 3 1
 1 3 2 1 0 0 1 0 1 1 3 3 3 0 3 0 4 0 1 1 1 0 0 1 1 1 3 3 3 3 0 0 1 1 1 1 3
 4 3 0 1 1 1 0 1 4 0 0 0 0 1 0 0 0 2 2 0 4 4 0 0 0 0 3 3 3 0 0 1 1 3 2 4 1
 1 4 4 0 4 3 1 4 4 0 0 3 3 1 3 0 0 0 3 0 0 3 4 4 4 4 3 0 4 4 3 0 3 1 3 4 4
 3 1 0 4 3 1 1 0 4 1 3 0 2 3 3 4 4 0 1 0 3 3 0 0 1 4 3 0 3 0 0 1 4 3 0 1 1
 1 0 3 3 0 3 4 4 0 4 0 1 0 0 0 1 2 0 4 1 0 0 0 4 1 0 4 4 3 3 3 4 0 0 4 3 3
 0 4 3 0 1 0 4 0 4 0 0 0 0 1 0 3 4 2 2 0 1 1 0 0 2 3 1 1 0 4 0 0 4 0 1 0 0
 0 4 3 3 3 0 0 0 0 0 0 3 0 0 1 1 1 2 2 2 0 0 3 1 4 0 1 4 0 4 0 3 3 3 4 4 3
 2 0 1 1 1 3 0 3 3 3 4 0 4 3 4 4 3 3 2 1 0 2 2 1 0 0 3 1 3 0 0 0 3 4 3 1 0
 1 1 0 0 1 0 3 3 2 0 3 4 0 4 0 2 0 3 3 3 1 3]
Inertia: 4552.733668281445

In [4]:
#Create a visualization of the results with 2 or 3 variables that you think will best
#differentiate the clusters

nba_df = pd.DataFrame(nba_scaled, columns = nba_data.columns) # Turning the scaled data into a df with "Player" and "Salary" columns

# Plotting the visualization

fig = px.scatter_3d(nba_df, x = "DRB", y = "PTS", z = "AST", color=kmeans_nba.labels_,
                    title = "Defensive Rebounds vs. Points vs. Assists")
fig.show(renderer="browser")

In [5]:
#Evaluate the quality of the clustering using total variance explained and silhouette scores

# Calculating total variance explained

total_ss = np.sum((nba_scaled - np.mean(nba_scaled))**2)
total = np.sum(total_ss)

SSE_clusters = (total - kmeans_nba.inertia_)
total_variance_explained = SSE_clusters/total
print(total_variance_explained)

# Calculating silhouette scores

silhouette_scores = []
for k in range(2, 11):
    kmeans_obj = KMeans(n_clusters = k, algorithm = "lloyd", random_state = 42).fit(nba_scaled)
    silhouette_scores.append(silhouette_score(nba_scaled, kmeans_obj.labels_))

print(silhouette_scores) # Printing the silhouette scores

0.45723251451103425
[np.float64(0.23273030897225094), np.float64(0.21097760898151272), np.float64(0.17833122715953764), np.float64(0.14666756161034122), np.float64(0.1286032972742622), np.float64(0.12797556333993346), np.float64(0.12651364152024897), np.float64(0.12309120234440826), np.float64(0.11658110094203179)]

In [6]:
#Determine the ideal number of clusters using the elbow method and the silhouette coefficient


# Elbow method

wcss = []
for i in range(1, 11):
    kmeans_basketball = KMeans(n_clusters = i, random_state = 42).fit(nba_scaled)
    wcss.append(kmeans_basketball.inertia_)

print(wcss) # Printing elbow method results
print(silhouette_scores) # Printing silhouette scores

[8388.000000000004, 6408.516070034209, 5551.64755154756, 4963.885372758339, 4552.733668281445, 4302.514477237274, 4134.8359701249, 3979.13163450283, 3919.6667674446426, 3791.0833726028445]
[np.float64(0.23273030897225094), np.float64(0.21097760898151272), np.float64(0.17833122715953764), np.float64(0.14666756161034122), np.float64(0.1286032972742622), np.float64(0.12797556333993346), np.float64(0.12651364152024897), np.float64(0.12309120234440826), np.float64(0.11658110094203179)]

In [7]:
#Visualize the results of the elbow method

elbow_data_nba = pd.DataFrame({"k": range(1, 11), "wcss": wcss})
fig = px.line(elbow_data_nba, x = "k", y = "wcss", title = "Elbow Method for Optimal k")
fig.update_layout(xaxis_title = "Number of Clusters (k)", yaxis_title = "Within-Cluster Sum of Squares (WCSS)")
fig.show(renderer = "browser")

KeyboardInterrupt:

In [8]:
#Use the recommended number of clusters

kmeans_nba_1 = KMeans(n_clusters = 3, random_state = 42).fit(nba_scaled) # Retraining the model with 3 clusters

# Plotting the visualization

fig = px.scatter_3d(nba_df, x = "DRB", y = "PTS", z = "AST", color=kmeans_nba_1.labels_,
                    title = "Defensive Rebounds vs. Points vs. Assists")
fig.show(renderer="browser")

In [ ]:
#Once again evaluate the quality of the clustering using total variance explained and silhouette scores

# Calculating total variance explained

total_ss_1 = np.sum((nba_scaled - np.mean(nba_scaled))**2)
total_1 = np.sum(total_ss_1)

SSE_clusters_1 = (total_1 - kmeans_nba_1.inertia_)
total_variance_explained_1 = SSE_clusters_1/total_1
print(total_variance_explained_1)

# Calculating silhouette scores

silhouette_scores_1 = []
for k in range(2, 11):
    kmeans_obj_1 = KMeans(n_clusters = k, algorithm = "lloyd", random_state = 42).fit(nba_scaled)
    silhouette_scores_1.append(silhouette_score(nba_scaled, kmeans_obj_1.labels_))

print(silhouette_scores_1) # Printing the silhouette scores

0.3381440687234668
[np.float64(0.23273030897225094), np.float64(0.21097760898151272), np.float64(0.17833122715953764), np.float64(0.14666756161034122), np.float64(0.1286032972742622), np.float64(0.12797556333993346), np.float64(0.12651364152024897), np.float64(0.12309120234440826), np.float64(0.11658110094203179)]

In [ ]:
#Use the model to select players for Mr. Rooney to consider

# Creating a final dataframe to analyze

nba_final_data = pd.merge(nba_performance_22[['Player']].join(nba_performance), nba_salaries_22, on = 'Player', how = 'inner')

nba_final_data = nba_final_data.dropna() # Dropping NA values

# Removing $ from the Salary column

nba_final_data['Salary'] = nba_final_data['Salary'].replace(r'[\$,]', '', regex = True)

# Creating a column to show which cluster each player was assigned to

nba_final_data["Cluster"] = kmeans_nba_1.labels_

# Defining the bad choices, good choices, and potential choices

bad_choices = nba_final_data[nba_final_data["Cluster"] == 0]

good_choices = nba_final_data[nba_final_data["Cluster"] == 1]

potential_choices = nba_final_data[nba_final_data["Cluster"] == 2]

# Dropping duplicate players

bad_choices = bad_choices.drop_duplicates(subset="Player")

good_choices = good_choices.drop_duplicates(subset="Player")

potential_choices = potential_choices.drop_duplicates(subset="Player")

# Printing 3 players for each category

print("Bad Choices:", bad_choices["Player"].head(3))
print("Good Choices:", good_choices["Player"].head(3))
print("Potential Choices", potential_choices["Player"].head(3))

nba_final_data.head(20)

Bad Choices: 3                Santi Aldama
4    Nickeil Alexander-Walker
9               Jose Alvarado
Name: Player, dtype: object
Good Choices: 7     Grayson Allen
13     Cole Anthony
14       OG Anunoby
Name: Player, dtype: object
Potential Choices 0    Precious Achiuwa
1        Steven Adams
2         Bam Adebayo
Name: Player, dtype: object

,Player,Age,G,GS,MP,FG%,3P%,2P%,eFG%,FT%,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Salary,Cluster
0,Precious Achiuwa,22.0,73.0,28.0,23.6,0.439,0.359,0.468,0.486,0.595,...,4.5,6.5,1.1,0.5,0.6,1.2,2.1,9.1,2840160,2
1,Steven Adams,28.0,76.0,75.0,26.3,0.547,0.000,0.548,0.547,0.543,...,5.4,10.0,3.4,0.9,0.8,1.5,2.0,6.9,17926829,2
2,Bam Adebayo,24.0,56.0,56.0,32.6,0.557,0.000,0.562,0.557,0.753,...,7.6,10.1,3.4,1.4,0.8,2.6,3.1,19.1,30351780,2
3,Santi Aldama,21.0,32.0,0.0,11.3,0.402,0.125,0.560,0.424,0.625,...,1.7,2.7,0.7,0.2,0.3,0.5,1.1,4.1,2094120,0
4,Nickeil Alexander-Walker,23.0,65.0,21.0,22.6,0.372,0.311,0.433,0.449,0.743,...,2.3,2.9,2.4,0.7,0.4,1.4,1.6,10.6,5009633,0
5,Nickeil Alexander-Walker,23.0,50.0,19.0,26.3,0.375,0.311,0.434,0.450,0.722,...,2.6,3.3,2.8,0.8,0.4,1.7,1.8,12.8,5009633,0
6,Nickeil Alexander-Walker,23.0,15.0,2.0,9.9,0.333,0.303,0.400,0.438,0.917,...,1.5,1.5,1.1,0.3,0.3,0.5,1.0,3.5,5009633,0
7,Grayson Allen,26.0,66.0,61.0,27.3,0.448,0.409,0.533,0.588,0.865,...,2.9,3.4,1.5,0.7,0.3,0.7,1.5,11.1,8500000,1
8,Jarrett Allen,23.0,56.0,56.0,32.3,0.677,0.100,0.688,0.678,0.708,...,7.3,10.8,1.6,0.8,1.3,1.7,1.7,16.1,20000000,2
9,Jose Alvarado,23.0,54.0,1.0,15.4,0.446,0.291,0.538,0.500,0.679,...,1.4,1.9,2.8,1.3,0.1,0.7,1.4,6.1,1563518,0
10,Kyle Anderson,28.0,69.0,11.0,21.5,0.446,0.330,0.481,0.484,0.638,...,4.3,5.3,2.7,1.1,0.7,1.0,1.6,7.6,8780488,0
11,Giannis Antetokounmpo,27.0,67.0,67.0,32.9,0.553,0.293,0.616,0.582,0.722,...,9.6,11.6,5.8,1.1,1.4,3.3,3.2,29.9,42492492,2
12,Thanasis Antetokounmpo,29.0,48.0,6.0,9.9,0.547,0.143,0.596,0.555,0.630,...,1.3,2.1,0.5,0.3,0.3,0.5,1.4,3.6,1878720,0
13,Cole Anthony,21.0,65.0,65.0,31.7,0.391,0.338,0.432,0.464,0.854,...,4.9,5.4,5.7,0.7,0.3,2.6,2.6,16.3,3613680,1
14,OG Anunoby,24.0,48.0,48.0,36.0,0.443,0.363,0.511,0.526,0.754,...,4.0,5.5,2.6,1.5,0.5,1.7,2.7,17.1,17357143,1
16,D.J. Augustin,34.0,55.0,2.0,16.1,0.423,0.415,0.448,0.577,0.884,...,1.0,1.2,1.9,0.3,0.0,1.0,0.7,5.3,333333,0
17,D.J. Augustin,34.0,34.0,2.0,15.0,0.404,0.406,0.400,0.548,0.868,...,1.0,1.2,2.2,0.3,0.0,1.3,0.5,5.4,333333,0
18,D.J. Augustin,34.0,21.0,0.0,17.8,0.453,0.426,0.556,0.622,1.000,...,1.1,1.3,1.6,0.3,0.0,0.5,1.0,5.3,333333,0
19,Deni Avdija,21.0,82.0,8.0,24.2,0.432,0.317,0.525,0.503,0.757,...,4.5,5.2,2.0,0.7,0.5,1.1,2.3,8.4,4916160,0
20,Deandre Ayton,23.0,58.0,58.0,29.5,0.634,0.368,0.642,0.639,0.746,...,7.7,10.2,1.4,0.7,0.7,1.6,2.4,17.2,30913750,2

#Write up the results in a separate notebook with supporting visualizations and 
an overview of how and why you made the choices you did. This should be at least 
500 words and should be written for a non-technical audience.